include (InstallRequiredSystemLibraries)
#license file path

SET (CPACK_RESOURCE_FILE_LICENSE   "${PROJECT_SOURCE_DIR}/LICENSE")
SET (CPACK_RESOURCE_FILE_README    "${PROJECT_SOURCE_DIR}/README")
SET(CPACK_PACKAGE_CONTACT "liyinbin@letv.com")

set (CPACK_GENERATOR "RPM")
set (CPACK_SOURCE_GENERATOR ${CPACK_SOURCE_ZIP})
set (CPACK_SOURCE_PACKAGE_FILE_NAME drill-source)
#set (CPACK_PACKAGE_INSTALL_DIRECTORY /usr/local/walle)
#message(STATUS "package type ${PACK}")
#set (CPACK_PACKAGING_INSTALL_PREFIX /usr/local/)

set (CPACK_PACKAGE_VERSION_MAJOR "${SNAPPY_MAJOR}")  
set (CPACK_PACKAGE_VERSION_MINOR "${SNAPPY_MINOR}") 
set (CPACK_PACKAGE_VERSION_PATCH ${SNAPPY_PATCHLEVEL})
include (CPack) 

